BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-pev-sim"
BBFILE_PATTERN_meta-pev-sim = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-pev-sim = "10"
LAYERSERIES_COMPAT_meta-pev-sim = "scarthgap"

LAYERDEPENDS_meta-pev-sim = "core meta-everest"
