# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/$USER/yocto-everest/poky/meta \
  /home/$USER/yocto-everest/poky/meta-poky \
  /home/$USER/yocto-everest/poky/meta-yocto-bsp \
  /home/$USER/yocto-everest/poky/meta-openembedded/meta-oe \
  /home/$USER/yocto-everest/poky/meta-openembedded/meta-python \
  /home/$USER/yocto-everest/poky/meta-openembedded/meta-networking \
  /home/$USER/yocto-everest/poky/meta-raspberrypi \
  /home/$USER/yocto-everest/poky/meta-everest \
  /home/$USER/yocto-everest/poky/meta-pev_sim \
  /home/$USER/yocto-everest/poky/meta-openjdk-temurin \
  "
