MACHINE = "raspberrypi3-64"

# Parallelization (adjust to your CPU)
BB_NUMBER_THREADS = "10"
PARALLEL_MAKE = "-j 10"

# Disk space monitoring
BB_DISKMON_DIRS = "STOPTASKS,${TMPDIR},1G,100K STOPTASKS,${DL_DIR},1G,100K"

# Add EVerest to image
IMAGE_INSTALL:append = " everest-core mosquitto python3 kernel-module-cdc-acm kernel-module-ch341 kernel-module-usbserial dieter-ev-driver python3-iso15118 openjdk-17-jre tshark" 


ENABLE_UART = "1"

DISTRO_FEATURES:append = " systemd usrmerge wifi"
INIT_MANAGER = "systemd"

LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

EVEREST_CORE_PATH = "/path/to/evereste"
BBMASK += "meta-everest/recipes-connectivity/openssl/"

# common download cache for all builds
DL_DIR = "/some/shared/directory"

# common sstate cache (reusable build artefacts)
SSTATE_DIR = "/another/shared/directory"

# root login without password
EXTRA_IMAGE_FEATURES += "debug-tweaks"

